Repository IP2B2/Front-End, pull requests merged in 2025-05, with the labels that each got.

#23 #homepage layout fixes
  src/app/home/components/Breadcrumbs.module.css
  src/app/home/homeLayout.module.css
  src/app/home/homePage.module.css
  src/app/home/layout.js
Labels: ready-to-run

#24 Form inchiriere Tip 1
  src/app/auth/form-inchiriere-1/formInchiriere.module.css
  src/app/auth/form-inchiriere-1/page.js
  src/app/page.js
Labels: queued

#28 #032 form inchiriere tip1 si tip 2 (am facut merge dintre #032 si #033 in #032)
  .github/workflows/auto-label.yml
  src/app/home/homeLayout.module.css
  src/app/home/inchiriere/form-inchiriere-1/page.js
  src/app/home/inchiriere/form-inchiriere-2/page.js
  src/app/home/inchiriere/formInchiriere.module.css
Labels: ready-to-run

#30 #043 sprint1 postfixes
  src/app/auth/extra-data-required/page.js
  src/app/auth/login/page.js
  src/app/auth/register/page.js
  src/app/home/components/Sidebar.js
  src/lib/components/form/Form.js
  src/lib/components/form/FormStyles.module.css
Labels: ready-to-run

#26 #035-Creare_pagina_individuala_produs
  public/icons/Frame 1000005448.svg
  public/icons/back-arrow.svg
  public/icons/buton-info.png
  public/icons/buton-info.svg
  public/icons/buton-logout.png
  public/icons/buton-logout.svg
  public/icons/buton-user-name.png
  public/icons/buton-user-name.svg
  public/icons/home-icon.png
  public/icons/slash-icon.png
  public/icons/slash-icon.svg
  src/app/home/components/Breadcrumbs.js
  src/app/home/components/TabletBreadcrumbs.js
  src/app/home/components/UserBox.js
  src/app/home/echipamente/echipament/Echipament.js
  src/app/home/echipamente/echipament/Echipament.module.css
  src/app/home/echipamente/echipament/page.js
  src/app/home/layout.js
  src/app/home/page.js
  src/lib/context.js
Labels: ready-to-run

#38 #035 build fixes
  src/app/home/echipamente/echipament/Echipament.module.css
  src/app/home/echipamente/echipament/page.js
Labels: ready-to-run

#37 #053-pagina-resetare-parola
  src/app/auth/forgot-password/forgotPassword.module.css
  src/app/auth/forgot-password/page.js
  src/app/auth/login/page.js
Labels: ready-to-run

#34 #044_Imbunatatire_landing_page_basic_design
  src/app/home/components/MobileNavbar.module.css
  src/app/home/homeLayout.module.css
  src/app/home/homePage.module.css
  src/app/home/page.js
Labels: ready-to-run

#41 #058-responsive-inchiriere
  src/app/home/inchiriere/formInchiriere.module.css
Labels: ready-to-run

#42 #057 validare pdf
  src/app/home/inchiriere/form-inchiriere-2/page.js
Labels: needs-work

#40 #056 finalizeaza buton si adaugare diacritice
  src/app/auth/extra-data-required/page.js
Labels: ready-to-run

#39 Pagina individuala produs dupa designul final
  public/icons/Frame 1000005448.svg
  public/icons/Frame 1000005450.svg
  src/app/home/components/Breadcrumbs.js
  src/app/home/components/Breadcrumbs.module.css
  src/app/home/components/MobileNavbar.module.css
  src/app/home/components/TabletBreadcrumbs.js
  src/app/home/components/TabletHeader.module.css
  src/app/home/echipamente/echipament/Echipament.js
  src/app/home/echipamente/echipament/Echipament.module.css
  src/app/home/echipamente/echipament/ProductImageCarousel.module.css
  src/app/home/echipamente/echipament/page.js
  src/app/home/homeLayout.module.css
Labels: ready-to-run

#44 #060 061 integrare login si laboratoare
  src/app/api/auth/login/route.js
  src/app/api/home/laboratoare/route.js
  src/app/auth/login/page.js
  src/app/home/homeLayout.module.css
  src/app/home/laboratoare/GridTable.module.css
  src/app/home/laboratoare/getLabs.js
  src/app/home/laboratoare/page.js
  src/lib/components/form/Form.js
  src/lib/logic/ApiCalls/AuthCalls.js
  src/lib/logic/ApiCalls/LabCalls.js
Labels: ready-to-run

#48 Mutat componentele și rezolvat importurile (SearchBar inclusiv)
  next.config.mjs
  public/icons/SearchIcon.png
  src/app/api/auth/login/route.js
  src/app/api/home/laboratoare/route.js
  src/app/home/echipamente/EchipamentePage.module.css
  src/app/home/echipamente/page.js
  src/lib/components/home/echipamente/ProductCard.js
  src/lib/components/home/echipamente/ProductCard.module.css
  src/lib/components/home/echipamente/ProductSearchAndFilter.module.css
  src/lib/components/home/echipamente/SearchAndFilter.js
  src/lib/components/home/echipamente/SearchAndFilter.module.css
  src/lib/components/home/echipamente/SearchBar.js
  src/lib/components/home/echipamente/SearchBar.module.css
Labels: ready-to-run

#50 Deployment testing DO NOT MERGE
  next.config.mjs
  public/icons/SearchIcon.png
  src/app/api/auth/login/route.js
  src/app/api/home/laboratoare/route.js
  src/app/home/echipamente/EchipamentePage.module.css
  src/app/home/echipamente/page.js
  src/lib/components/home/echipamente/ProductCard.js
  src/lib/components/home/echipamente/ProductCard.module.css
  src/lib/components/home/echipamente/ProductSearchAndFilter.module.css
  src/lib/components/home/echipamente/SearchAndFilter.js
  src/lib/components/home/echipamente/SearchAndFilter.module.css
  src/lib/components/home/echipamente/SearchBar.js
  src/lib/components/home/echipamente/SearchBar.module.css
Labels: ready-to-run

#49 #066 componenta listare cerere
  src/app/home/testing/listare-cerere/page.js
  src/lib/components/home/CerereListing.js
  src/lib/components/home/CerereListing.module.css
  src/lib/routes.js
Labels: ready-to-run

#51 Hotfix
  src/lib/components/home/echipamente/SearchAndFilter.js
Labels: ready-to-run

#53 #086-Pagina confirmare decizie admin
  src/app/home/confirmare-decizie-admin/confirmDecisionAdmin.module.css
  src/app/home/confirmare-decizie-admin/page.js
  src/lib/routes.js
Labels: ready-to-run

#52 #065 preview cerere
  src/app/home/echipamente/echipament/page.js
  src/app/home/testing/cerere-preview/cererePreview.module.css
  src/app/home/testing/cerere-preview/page.js
  src/app/home/testing/search-and-filter/page.js
  src/lib/components/form/Form.js
  src/lib/components/form/FormStyles.module.css
  src/lib/components/home/PreviewCerere.js
  src/lib/components/home/PreviewCerere.module.css
  src/lib/routes.js
Labels: ready-to-run

#58 Fix: export broken in routes.js (missing bracket)
  src/lib/routes.js
Labels: ready-to-run

#57 #068 componenta listare cerere laborant
  package-lock.json
  package.json
  src/app/home/testing/listare-cerere/page.js
  src/lib/components/home/echipamente/CerereLIistingLaborant.module.css
  src/lib/components/home/echipamente/CerereListingLaborant.js
Labels: ready-to-run

#55 #082 form adaugare produs
  src/app/home/form-adaugare-produs/formAdaugareProdus.module.css
  src/app/home/form-adaugare-produs/page.js
Labels: ready-to-run

#60 #092 - Componenta listare users
  src/app/home/testing/listare-cerere/page.js
  src/lib/components/home/echipamente/ListareUser.js
  src/lib/components/home/echipamente/ListareUser.module.css
Labels: ready-to-run

#61 '#091_Componenta LISTARE PRODUS'
  src/lib/components/home/echipamente/ProdusListing.js
  src/lib/components/home/echipamente/ProdusListing.module.css
Labels: ready-to-run

#54 #083 Produsul a fost adaugat cu succes
  package-lock.json
  src/app/home/produs-adaugat-succes/page.js
  src/app/home/produs-adaugat-succes/produsAdaugatSucces.module.css
  src/lib/routes.js
Labels: ready-to-run

#65 Hotfix routes broke again
  src/lib/routes.js
Labels: ready-to-run

#67 #094 - fix componenta listare produs
  src/app/home/testing/listare-cerere/page.js
  src/lib/components/home/echipamente/ProdusListing.js
  src/lib/components/home/echipamente/ProdusListing.module.css
  src/lib/fonts/Montserrat.js
Labels: ready-to-run

#66 #087-cerere-useri
  src/app/home/cereri-useri/cereriUseri.module.css
  src/app/home/cereri-useri/page.js
Labels: ready-to-run

#70 #089 administrare cereri laborant
  src/app/home/cereri-laborant/adminCereriLaborant.module.css
  src/app/home/cereri-laborant/page.js
Labels: ready-to-run

#71 #106 popup confirmare adaugare produs
  public/animated-characters/jumping.svg
  src/app/home/testing/adaugare-produs/page.js
  src/app/home/testing/adaugare-produs/page.module.css
  src/lib/components/home/MobileNavbar.module.css
  src/lib/components/popups/ProductAddedSucc.js
  src/lib/components/popups/ProductAddedSucc.module.css
Labels: needs-work

#76 Update routes.js hotfix
  src/lib/routes.js
Labels: ready-to-run

#72 #105 pagina listare cereri admin
  src/app/home/cereri-admin/listareCereriAdmin.module.css
  src/app/home/cereri-admin/page.js
Labels: ready-to-run

#73 #108-componenta-listare-cerere-laborant
  env
  src/app/home/testing/listare-cerere/page.js
  src/lib/components/home/echipamente/CerereLIistingLaborant.module.css
  src/lib/components/home/echipamente/CerereListingLaborant.js
Labels: ready-to-run

#77 #109 componenta listare cerere admin
  src/app/home/cereri-useri/page.js
  src/app/home/testing/listare-cerere/page.js
  src/lib/components/home/CerereListing.js
  src/lib/components/home/CerereListing.module.css
  src/lib/components/home/echipamente/CerereListingAdmin.js
  src/lib/components/home/echipamente/CerereListingAdmin.module.css
  src/lib/components/home/echipamente/CerereListingStudent.js
  src/lib/components/home/echipamente/CerereListingStudent.module.css
Labels: ready-to-run

#56 #080-Pagina_admin
  public/icons/administrare_echipamente.svg
  public/icons/administrare_utilizatori.svg
  public/icons/icon-administrare.svg
  src/app/home/administrare/administrarePage.module.css
  src/app/home/administrare/page.js
  src/lib/components/home/HomeHeader.js
  src/lib/components/home/Sidebar.js
  src/lib/components/home/Sidebar.module.css
  src/lib/fonts/Montserrat.js
Labels: needs-work

#83 #101-Vizualizare_detalii_user-ca-admin
  src/app/home/testing/administrare/administrare-utilizatori/administrareUtilizatori.module.css
  src/app/home/testing/administrare/administrare-utilizatori/page.js
  src/lib/components/popups/UserDetailsPopup.js
  src/lib/components/popups/UserDetailsPopup.module.css
Labels: ready-to-run

#63 #085-Popup-formular-utilizator-asignare-rol
  src/app/home/testing/administrare/utilizatori/cereri-rol/page.js
  src/lib/components/admin/RoleRequestPopup.js
  src/lib/components/admin/RoleRequestPopup.module.css
  src/lib/components/home/echipamente/ListareUser.js
Labels: ready-to-run

#69 #090-Formular-utilizator-inchiriere-produs-accept/reject
  src/app/home/testing/product-request-popup/page.js
  src/lib/components/home/ProductRequestPopup.js
  src/lib/components/home/ProductRequestPopup.module.css
  src/lib/routes.js
Labels: ready-to-run

#74 #107-componenta-listare-cerere-student/cercetator
  src/app/home/testing/listare-cerere/page.js
  src/lib/components/home/echipamente/CerereListingStudent.js
Labels: ready-to-run

#78 #100_Vizualizare_detalii_produs-ca-admin
  src/app/home/administrare/administrare-echipamente/page.js
  src/lib/components/home/Sidebar.js
  src/lib/components/home/Sidebar.module.css
  src/lib/components/home/echipamente/AdaugareProdusPopup.js
  src/lib/components/home/echipamente/AdaugareProdusPopup.module.css
Labels: needs-work

#82 #111 - redirectionari pagini
  src/app/home/administrare/administrare-echipamente/listareProduseAdmin.module.css
  src/app/home/administrare/administrare-echipamente/page.js
  src/app/home/administrare/page.js
  src/app/home/cereri-useri/page.js
  src/app/home/cereri/administrareUseri.module.css
  src/app/home/cereri/page.js
  src/app/home/echipamente/echipament/Echipament.module.css
  src/app/home/echipamente/echipament/page.js
  src/app/home/form-adaugare-produs/page.js
  src/app/home/inchiriere/echipament-complex/page.js
  src/app/home/inchiriere/echipament-simplu/page.js
  src/app/home/inchiriere/formInchiriere.module.css
  src/lib/components/home/Sidebar.js
  src/lib/components/home/echipamente/ListareUser.js
  src/lib/components/home/echipamente/ListareUser.module.css
  src/lib/components/home/echipamente/ProductCard.js
  src/lib/components/home/echipamente/ProdusListing.js
  src/lib/components/home/echipamente/ProdusListing.module.css
  src/lib/components/home/echipamente/RequestDetailsPopup.js
Labels: ready-to-run

#87 #int-fe5 created automated tree of links
  src/app/page.js
  src/app/testing/page.js
  src/lib/getRoutes.js
  src/lib/routes.js
Labels: ready-to-run

#93 samearga
  src/app/acasa/echipamente/echipament/[equipmentId]/page.js
  src/app/acasa/echipamente/echipamentePage.module.css
  src/app/acasa/echipamente/page.js
  src/app/auth/register/page.js
  src/app/page.js
  src/app/rootPage.module.css
  src/lib/actions/getAllEquipments.js
  src/lib/actions/performInitialRegister.js
  src/lib/components/auth/authBannerContainer.js
  src/lib/components/home/Sidebar.js
  src/lib/components/home/echipamente/SearchAndFilter.js
Labels: to-review

#95 added equipments CRUD, /test page, getSessionToken util function
  src/app/test/page.js
  src/lib/actions/equipmentActions.js
  src/lib/getSessionToken.js
Labels: ready-to-run
